apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: studyroom
  namespace: argocd
spec:
  project: default
  source:
    repoURL: https://github.com/urban-jungle/studyroom-deploy-repo
    targetRevision: main
    path: k8s
  destination:
    server: https://kubernetes.default.svc
    namespace: studyroom
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
