apiVersion: v1
kind: Pod
metadata:
  name: studyroom-db
  labels:
    app: studyroom-db
spec:
  containers:
    - name: mariadb
      image: mariadb:10.6
      env:
        - name: MYSQL_ROOT_PASSWORD
          value: root
        - name: MYSQL_DATABASE
          value: studyroom
      ports:
        - containerPort: 3306
      volumeMounts:
        - name: db-storage
          mountPath: /var/lib/mysql
  volumes:
    - name: db-storage
      emptyDir: {}
